# Generated by Django 3.0.3 on 2020-02-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('portada', models.ImageField(upload_to='static/css/')),
                ('descripcion', models.TextField()),
                ('edadMinima', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Butaca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Sesiones')),
            ],
        ),
    ]
